/* Auremgrid dashboard completion layer. No build step and no fabricated metrics. */
(function(){
  'use strict';
  const esc=v=>{const d=document.createElement('div');d.textContent=v==null?'':String(v);return d.innerHTML};
  const unknown=v=>v===null||v===undefined||v===''?'Unknown':String(v);
  const token=()=>localStorage.getItem('auremgrid_session')||'';
  async function get(path){const headers={};const t=token();if(t)headers.Authorization=`Bearer ${t}`;const r=await fetch(path,{headers});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()}
  function stateClass(s){return String(s||'unknown').toLowerCase().replace(/[^a-z0-9_-]/g,'-')}
  function honest(kind,title,detail){return `<div class="empty honest-state ${esc(kind)}"><b>${esc(title)}</b><br>${esc(detail)}</div>`}
  function scalar(row,keys){for(const k of keys)if(row&&row[k]!==null&&row[k]!==undefined&&row[k]!=='')return row[k];return null}
  function ownerLabel(value){if(!value)return 'Unknown';if(typeof value==='string')return value;return value.name||value.person_id||value.id||'Unknown'}
  function scopeLabel(value){if(!value||value.status==='unknown')return 'Unknown';return value.percentage==null?'Unknown':`${value.percentage}%`}
  function revenueLabel(client){const finance=client&&client.finance||{};if(finance.status!=='connected')return 'Not connected';return finance.recognized_revenue==null?'Unknown':String(finance.recognized_revenue)}
  function renderValue(value){if(value===null||value===undefined||value==='')return 'Unknown';if(Array.isArray(value))return value.length?value.map(renderValue).join('; '):'None';if(typeof value==='object')return Object.entries(value).map(([key,item])=>`${key.replaceAll('_',' ')}: ${renderValue(item)}`).join('; ');return String(value)}
  function insertAfter(node,el){node.parentNode&&node.parentNode.insertBefore(el,node.nextSibling)}

  function renderAgencyExtras(data){
    const command=document.getElementById('page-command');if(!command)return;
    let host=document.getElementById('dashboard-completion-overview');if(!host){host=document.createElement('div');host.id='dashboard-completion-overview';host.className='grid';const metrics=document.getElementById('metrics');if(metrics)insertAfter(metrics,host);else command.appendChild(host)}
    const wings=Array.isArray(data.agency_map)?data.agency_map:Array.isArray(data.wings)?data.wings:[];
    const nodes=wings.length?wings.map(w=>`<article class="agency-node"><strong>${esc(w.name||w.label||w.id||'Operating object')}</strong><small>${esc(w.kind||w.source||'Canonical object')}</small><span class="state ${stateClass(w.state||w.status)}">${esc(unknown(w.state||w.status))}</span></article>`).join(''):honest('empty','Agency map unavailable','No agency_map or wings records were returned by /dashboard/data; no structure is inferred.');
    const trendSource=data.trends||data.history||data.metrics_history||{};
    const trends=Array.isArray(trendSource)?trendSource:Object.entries(trendSource).flatMap(([series,points])=>(Array.isArray(points)?points:[]).map(point=>({...point,series})));
    const trendHtml=trends.length?trends.slice(-18).map(t=>`<div class="trend-cell"><b>${esc(unknown(scalar(t,['value','count','total'])))}</b><span>${esc(`${String(t.series||'trend').replaceAll('_',' ')} · ${t.label||t.period||t.date||'period unknown'}`)}</span></div>`).join(''):honest('empty','Trend history unavailable','No trend series was returned by the backend.');
    const attention=Array.isArray(data.attention)?data.attention:Array.isArray(data.queue)?data.queue:(data.cosmo&&Array.isArray(data.cosmo.queue)?data.cosmo.queue:[]);
    const actionHtml=attention.length?`<table class="overview-action-table"><thead><tr><th>Surface</th><th>Reason</th><th>Evidence</th><th>Next action</th></tr></thead><tbody>${attention.map(a=>`<tr><td>${esc(a.surface||'Command')}</td><td>${esc(a.reason||a.title||'Unlabelled')}</td><td>${esc(a.evidence||a.source_type||'Unknown')}</td><td>${esc(a.next_action||'Review')}</td></tr>`).join('')}</tbody></table>`:honest('empty','Action table is empty','No ranked interventions were returned for this permitted scope.');
    host.innerHTML=`<section class="card wide"><h2>Agency map</h2><p class="sub">Only operating wings returned by the canonical ledger are shown.</p><div class="agency-map">${nodes}</div></section><section class="card narrow"><h2>Trends</h2><p class="sub">Historical values are shown only when sourced.</p><div class="trend-strip">${trendHtml}</div></section><section class="card full"><h2>Action table</h2>${actionHtml}</section>`;
  }
  function renderClientPortfolio(data){
    const clients=Array.isArray(data.clients)?data.clients:[];for(const id of ['clients','client-portfolio']){const target=document.getElementById(id);if(!target)continue;if(!clients.length){target.innerHTML=honest('empty','No client portfolio records','No permitted client workspaces were returned by /dashboard/data.');continue}target.innerHTML=`<table class="dense-table client-portfolio-table"><thead><tr><th>Client</th><th>Owner</th><th>Health</th><th>Attention</th><th>Scope usage</th><th>Sourced revenue</th><th>Work</th><th>Review</th><th>Risk</th><th>Last touch</th></tr></thead><tbody>${clients.map(c=>`<tr data-client="${esc(c.id)}"><td><b>${esc(unknown(c.name||c.id))}</b></td><td>${esc(ownerLabel(c.owner||c.owner_name||c.owner_person_id))}</td><td>${esc(unknown(c.health))}</td><td>${esc(unknown(c.attention||c.attention_state))}</td><td>${esc(scopeLabel(c.scope||c.scope_usage||c.scope_utilization))}</td><td>${esc(revenueLabel(c))}</td><td>${esc(unknown(c.open_work))}</td><td>${esc(unknown(c.reviews))}</td><td>${esc(unknown(c.risks))}</td><td>${esc(unknown(c.last_touch))}</td></tr>`).join('')}</tbody></table>`;}
  }
  function renderAnnotationIA(){const page=document.getElementById('page-review');if(!page||document.getElementById('annotation-ia'))return;const box=document.createElement('section');box.id='annotation-ia';box.className='card annotation-ia';box.innerHTML='<h2>Review and annotation workspace</h2><p class="sub">Annotations stay attached to evidence and remain permission-scoped. Rich media controls appear only when the source contract provides them.</p><div class="annotation-lanes"><div class="annotation-lane"><h3>Evidence anchor</h3><p>Document, image, video, or URL reference with provenance.</p></div><div class="annotation-lane"><h3>Region or timestamp</h3><p>Coordinates and time ranges are unknown until a source supplies them.</p></div><div class="annotation-lane"><h3>Reviewer decision</h3><p>Approve, reject, or request changes through a capability-gated action.</p></div><div class="annotation-lane"><h3>Audit trail</h3><p>Every annotation change remains attributable and append-only.</p></div></div>';page.appendChild(box)}
  function renderAgentTelemetry(){document.querySelectorAll('.agent-worker-card').forEach(card=>{const heading=card.querySelector('h2'),agent=(completionData&&completionData.agents||[]).find(item=>String(item.name||item.id)===String(heading&&heading.textContent)),runtime=agent&&agent.runtime||{},prior=card.querySelector('.agent-telemetry');if(prior)prior.remove();const values=[['Level',agent&&agent.level||'Not reported'],['Budget',runtime.budget_status==='not_configured'?'Not configured':unknown(runtime.budget)],['Cost',unknown(runtime.cost)],['Quality',runtime.quality_rate==null?'Not enough runs':`${Math.round(runtime.quality_rate*100)}%`],['Queue',unknown(runtime.queue_count)],['Failures',unknown(runtime.failed_runs)]];card.insertAdjacentHTML('beforeend',`<div class="agent-telemetry">${values.map(([k,v])=>`<div><b>${k}</b><span>${esc(v)}</span></div>`).join('')}</div><p class="source-note">Sourced from agent tasks and runs; unavailable budget remains not configured.</p>`)});
  }
  async function enrichClient(data){
    const body=document.getElementById('client-body');if(!body)return;
    const tabs=document.getElementById('client-tabs');if(tabs&&!tabs.querySelector('[data-tab="Insights"]')){const b=document.createElement('button');b.type='button';b.dataset.tab='Insights';b.textContent='Insights';b.onclick=()=>paintInsights(data);tabs.appendChild(b)}
    function paintInsights(d){const groups=d.insights||{};body.innerHTML=`<section class="card module"><span class="state">Evidence view</span><h2>Client insights</h2><p class="sub">Canonical performance insights, forecasts, opportunities, and campaign anomalies for this client.</p><div class="client-insight-grid">${Object.entries(groups).map(([kind,rows])=>`<div class="insight-tile"><b>${esc(kind.replaceAll('_',' '))}</b><span>${esc(Array.isArray(rows)&&rows.length?rows.slice(0,5).map(row=>row.evidence_summary||row.reason||row.explanation||row.forecast_type||row.id).join('; '):'No records')}</span></div>`).join('')||'<div class="insight-tile"><b>Insights</b><span>No records</span></div>'}</div></section>`}
    if(data&&data.workspace)return;
    const clientId=data&&data.id||data&&data.workspace_id;try{const auth=await get('/auth/me');const query=clientId?`&workspace_id=${encodeURIComponent(clientId)}`:'';const fetched=await get(`/dashboard/client?organization_id=${encodeURIComponent(auth.organization_id)}&person_id=${encodeURIComponent(auth.person_id)}${query}`);data=fetched||data||{};}catch(_){data=data||{}}
    if(data&&data.workspace)paintInsights(data);
  }
  async function enrichWork(id){try{const auth=await get('/auth/me');const org=auth.organization_id,person=auth.person_id,active=document.querySelector('[data-space-id].active'),workspaceId=active&&active.dataset.spaceId;if(!workspaceId)throw new Error('No selected workspace');const detail=await get(`/work/detail?organization_id=${encodeURIComponent(org)}&workspace_id=${encodeURIComponent(workspaceId)}&person_id=${encodeURIComponent(person)}&work_item_id=${encodeURIComponent(id)}`);const item=detail.work_item||detail;const body=document.getElementById('inspector-body')||document.getElementById('detail-body');if(!body)return;const rows=[['Reviewer',scalar(item,['reviewer','reviewer_name','reviewer_person_id'])],['Definition of Done',scalar(item,['definition_of_done','dod'])],['Dependencies',detail.dependencies],['Brain context',scalar(item,['brain_context','context'])],['Files',detail.files],['Versions',detail.versions],['Reviews',detail.reviews],['Review comments',detail.review_comments],['Activity',detail.comments]];const html=`<section class="detail-section work-enrichment-section"><h3>Delivery context</h3><div class="work-enrichment-grid">${rows.map(([k,v])=>`<div class="work-enrichment"><b>${k}</b><span>${esc(renderValue(v))}</span></div>`).join('')}</div></section>`;if(!body.querySelector('.work-enrichment-section'))body.insertAdjacentHTML('beforeend',html)}catch(_){/* Existing inspector remains usable when extended fields are unavailable. */}}
  function renderScenarios(){const root=document.getElementById('intelligence-findings');if(!root||root.querySelector('.scenario-grid'))return;const cards=[...root.querySelectorAll('.intelligence-card')];const scenarios=[];cards.forEach(c=>{const text=c.textContent||'';if(/scenario/i.test(text))scenarios.push({title:text.slice(0,120)})});if(!scenarios.length)return;const section=document.createElement('section');section.className='scenario-grid';section.innerHTML=scenarios.map(s=>`<article class="scenario-card"><header><h3>${esc(s.title)}</h3><span class="state">Modeled</span></header><ul><li>Assumptions: Unknown unless returned</li><li>Domain impacts: Unknown unless returned</li><li>Constraints: Unknown unless returned</li><li>Mitigations: Unknown unless returned</li></ul><div class="scenario-actions"><button type="button" disabled title="No capability descriptor returned">No action available</button></div></article>`).join('');root.appendChild(section)}
  let completionData=null;
  function renderScenarioData(data){
    const root=document.getElementById('intelligence-findings'),scenarios=[...(Array.isArray(data&&data.scenarios)?data.scenarios:[]),...(data&&data.findings||[]).flatMap(finding=>finding.scenarios||[])];if(!root||!scenarios.length)return;
    const old=root.querySelector('.scenario-grid');if(old)old.remove();
    const section=document.createElement('section');section.className='scenario-grid';
    section.innerHTML=scenarios.map(s=>{const assumptions=s.assumptions||s.assumption||[],impacts=s.domain_impacts||s.impacts||s.impact,constraints=s.constraints||s.downside_constraints||[],mitigations=s.mitigations||s.mitigation||[],actions=s.action_descriptors||s.allowed_actions||[],actionButtons=actions.length?actions.map(a=>a&&a.route?`<button type="button" data-scenario-action="${esc(JSON.stringify(a))}">${esc(a.label||a.action||'Open action')}</button>`:`<button type="button" disabled title="No backend route is available">${esc(a&&a.label||a&&a.action||'Action')} unavailable</button>`).join(''):'<button type="button" disabled title="No capability descriptor returned">No action available</button>';return `<article class="scenario-card"><header><h3>${esc(s.title||s.name||s.id||'Scenario')}</h3><span class="state">${esc(unknown(s.status||'Modeled'))}</span></header><p class="sub">${esc(s.summary||s.description||s.downside||'Scenario detail returned by the evidence service.')}</p><ul><li>Inputs: ${esc(renderValue(s.retained_inputs))}</li><li>Assumptions: ${esc(renderValue(assumptions))}</li><li>Domain impacts: ${esc(renderValue(impacts))}</li><li>Constraints: ${esc(renderValue(constraints))}</li><li>Mitigations: ${esc(renderValue(mitigations))}</li><li>Confidence: ${esc(renderValue(s.confidence))}</li></ul><div class="scenario-actions">${actionButtons}</div></article>`}).join('');root.appendChild(section);
    section.querySelectorAll('[data-scenario-action]').forEach(button=>button.onclick=()=>{try{const a=JSON.parse(button.dataset.scenarioAction);if(typeof window.executeDescriptorAction==='function')window.executeDescriptorAction(a)}catch(_){}});
  }
  function renderIntelligenceCompletion(data){const root=document.getElementById('intelligence-findings');if(!root)return;const plan=data&&data.recommended_plan,deliberation=data&&data.deliberation,evaluation=data&&data.recommendation_evaluation;if(!plan&&!deliberation&&!evaluation)return;root.querySelector('.intelligence-completion')?.remove();const box=document.createElement('section');box.className='intelligence-card intelligence-completion';const reviews=deliberation&&deliberation.agents||[];box.innerHTML=`<div class="intelligence-card-body"><div class="intelligence-label"><span>Decision support</span><span class="intelligence-confidence">Read only until approved</span></div>${plan?`<div class="intelligence-impact"><b>Cross-wing plan</b><p>${esc(plan.goal||'No goal returned')}</p>${(plan.steps||[]).map(step=>`<p>${esc(`${step.wing||'Wing'} · ${step.title||step.action||step.id} · dependencies ${renderValue(step.depends_on)} · deadline ${renderValue(step.deadline)} · risks ${renderValue(step.risks)}`)}</p>`).join('')}</div>`:''}${reviews.length?`<div class="intelligence-impact"><b>Structured challenge</b>${reviews.map(row=>`<p>${esc(`${row.agent} · ${row.stance} · ${row.summary}`)}</p>`).join('')}</div>`:''}${evaluation?`<div class="intelligence-impact"><b>Recommendation calibration</b><p>${esc(renderValue(evaluation))}</p></div>`:''}</div>`;root.appendChild(box)}
  let intelligenceContext={type:'workspace',id:null,label:'Selected workspace'};
  function selectedWorkspace(){const active=document.querySelector('[data-space-id].active');return active&&active.dataset.spaceId}
  function setIntelligenceContext(type,id,label){intelligenceContext={type:type||'workspace',id:id||selectedWorkspace(),label:label||type||'Selected workspace'};const target=document.getElementById('intelligence-scope');if(target)target.textContent=`${intelligenceContext.label} · ${intelligenceContext.type}`}
  function installScenarioControls(){const rail=document.getElementById('intelligence-rail'),anchor=rail&&rail.querySelector('.intelligence-prompts');if(!rail||!anchor||document.getElementById('what-if-form'))return;const form=document.createElement('form');form.id='what-if-form';form.className='what-if-form';form.innerHTML='<b>Simulate a bounded change</b><div class="what-if-grid"><label>Capacity hours<input name="capacity_hours_delta" type="number" step="0.5" value="0"></label><label>Work hours<input name="work_hours_delta" type="number" step="0.5" value="0"></label><label>Scope units<input name="scope_usage_delta" type="number" step="0.5" value="0"></label><label>Finance delta<input name="finance_amount_delta" type="number" step="1" value="0"></label><label>Health delta<input name="client_health_delta" type="number" step="0.01" value="0"></label><label>Deadline days<input name="deadline_days_delta" type="number" step="1" value="0"></label></div><button type="submit">Run scenario</button><small>Inputs, assumptions, constraints, evidence and confidence are retained. Nothing is executed.</small>';anchor.insertAdjacentElement('afterend',form);form.onsubmit=async event=>{event.preventDefault();const workspaceId=selectedWorkspace(),status=document.getElementById('intelligence-status');if(!workspaceId){if(status)status.textContent='Select a workspace';return}if(status)status.textContent='Modeling permitted evidence';try{const auth=await get('/auth/me'),values=new FormData(form),params=new URLSearchParams({organization_id:auth.organization_id,workspace_id:workspaceId,person_id:auth.person_id,context_type:intelligenceContext.type,context_id:intelligenceContext.id||workspaceId});for(const [key,value] of values.entries())params.set(`what_if_${key}`,String(value));const data=await get(`/dashboard/intelligence?${params}`);if(typeof window.renderIntelligence==='function')window.renderIntelligence(data);if(status)status.textContent=`${(data.findings||[]).length} finding(s) · scenario modeled`}catch(error){if(status)status.textContent=`Scenario unavailable · ${error.message}`}}}
  async function boot(){try{const auth=await get('/auth/me');completionData=await get(`/dashboard/data?organization_id=${encodeURIComponent(auth.organization_id)}&person_id=${encodeURIComponent(auth.person_id)}`);renderAgencyExtras(completionData);renderClientPortfolio(completionData)}catch(_){/* Inline dashboard renderer owns degraded state. */}const rail=document.getElementById('intelligence-rail');if(rail){rail.setAttribute('aria-label','Cosmo · Auremgrid Intelligence');const kicker=rail.querySelector('.intelligence-kicker');if(kicker)kicker.textContent='Cosmo · Auremgrid Intelligence'}if(typeof window.renderIntelligence==='function'&&!window.__completionIntelligenceWrapped){const base=window.renderIntelligence;window.renderIntelligence=function(data){base(data);renderScenarioData(data);renderIntelligenceCompletion(data)};window.__completionIntelligenceWrapped=true}installScenarioControls();renderAnnotationIA();renderAgentTelemetry();renderScenarios();setIntelligenceContext('workspace',selectedWorkspace(),'Selected workspace');document.addEventListener('click',e=>{const work=e.target.closest&&e.target.closest('[data-work-id]');if(work){setIntelligenceContext('work',work.dataset.workId,work.textContent.trim().slice(0,70));setTimeout(()=>enrichWork(work.dataset.workId),80)}const client=e.target.closest&&e.target.closest('[data-client]');if(client){setIntelligenceContext('client',client.dataset.client,client.querySelector('b')?.textContent||'Client');if(typeof window.openClient==='function')window.openClient(client.dataset.client);setTimeout(()=>enrichClient({id:client.dataset.client}),120)}const project=e.target.closest&&e.target.closest('[data-project-id]');if(project)setIntelligenceContext('project',project.dataset.projectId,project.textContent.trim().slice(0,70));const campaign=e.target.closest&&e.target.closest('[data-campaign-id]');if(campaign)setIntelligenceContext('campaign',campaign.dataset.campaignId,campaign.textContent.trim().slice(0,70));const personNode=e.target.closest&&e.target.closest('[data-person-id]');if(personNode)setIntelligenceContext('person',personNode.dataset.personId,personNode.textContent.trim().slice(0,70));const nav=e.target.closest&&e.target.closest('.nav button[data-name]');if(nav)setIntelligenceContext('workspace',selectedWorkspace(),nav.dataset.name)},{capture:true});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
  setInterval(()=>{renderAnnotationIA();renderAgentTelemetry();renderScenarios();if(completionData)renderClientPortfolio(completionData)},1500);
})();
